### ISSUE TITLE
deficient indentation after @context (swagger/apiary)

### ISSUE THREAD

**Issue by manoadamro** [AtomLinter/linter-js-yaml#127]
when using:
```yaml
example:
      '@context':
        '@vocab'              : 'http://schema.org/'
        'fake'                    : 'http://fake.co.uk/'
      some: thing
      other: thing
```

every line after this until the end of the end of the model definition is marked with warning 'deficient indentation' even though it is valid in both swagger and apiary.
