### ISSUE TITLE
Ability to Add Custom Tags

### ISSUE THREAD

**Issue by ajmath** [AtomLinter/linter-js-yaml#2]
We're using https://github.com/EverythingMe/rainbow/ to manage AWS CloudFormation templates and the linter is not happy with some of it's built-in tags.

For example, the following usage is valid but the linter is not happy with it.
```
Resources:
    RootRole:
      Properties:
        Policies:
          - !yaml AmazonS3ReadOnlyAccess:config/policies.yaml
```
