### ISSUE TITLE
Ability to specify custom tag types

### ISSUE THREAD

**Issue by hellgiver** [AtomLinter/linter-js-yaml#91]
linter errors on custom tags for being incorrect type, looks like all custom tags are declared as scalar without the option for sequence.  The code below is a snippet from an AWS CloudFormation template that I tested as valid.  You can see where the linter has issues in the comments.

```
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidrBlock0
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
#This format is happy with linter
      - Key: Name
        Value:
          Fn::Join:
          - "-"
          - - Ref: AWS::StackName
            - VPC
#This format is happy with linter
      - Key: NameYAMLgood1
        Value:
          "Fn::Join": [ "-", [ Ref: "AWS::StackName", VPC ] ]
#This format is happy with linter
      - Key: NameYAMLgood2
        Value: !Join [ "-", [ Ref: "AWS::StackName", VPC ] ]
#This format errors with
# unacceptable node kind for !<!Ref> tag; it should be "sequence", not "scalar"
      - Key: NameYAMLerror1
        Value:
          "Fn::Join": [ "-", [ !Ref "AWS::StackName", VPC ] ]
#This format errors with
# unacceptable node kind for !<!Ref> tag; it should be "sequence", not "scalar"
      - Key: NameYAMLerror2
        Value: !Join [ "-", [ !Ref "AWS::StackName", VPC ] ]
```

Some links
[AWS Cloudformation YAML announcement](https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/)
[AWS CloudFormation Intrinsic Functions List](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)
