### ISSUE TITLE
Duplicate keys

### ISSUE THREAD

**Issue by gilesbutler** [AtomLinter/linter-js-yaml#98]
Hey guys,

Thanks for this package. I'm very new to YAML so I don't know if this is a feature of the language or if my linter just isn't working properly.
But is it possible to show an error for duplicate keys:

```
states:
    state1: text
    state2: text
    state1: text
```

The second ```state1``` would cause an error. 

Thanks
